export enum BlockComponentType {
    LktBox = 'lkt-box',
    LktAccordion = 'lkt-accordion',
    LktIcon = 'lkt-icon',
    LktColor = 'lkt-color',
    Columns = 'columns',
    Colors = 'colors',
    Header1 = 'h1',
    Header2 = 'h2',
    Header3 = 'h3',
    Text = 'text',
    BulletList = 'ul',
    ListItem = 'li',
    Item = 'item',
    Basic = 'basic',
    LmmMultimediaImage = 'lmm-multimedia:image',
}